apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: kafka
      app.kubernetes.io/component: kafka
      app.kubernetes.io/instance: kafka
    name: kafka
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: docker.io/bitnami/kafka:latest
      from:
        kind: DockerImage
        name: docker.io/bitnami/kafka:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: kafka
      app.kubernetes.io/component: kafka
      app.kubernetes.io/instance: kafka
      app.kubernetes.io/part-of: vote-application
    name: kafka
  spec:
    replicas: 1
    selector:
      deploymentconfig: kafka
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deploymentconfig: kafka
      spec:
        containers:
        - env:
          - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
            value: CONTROLLER
          - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
            value: 0@localhost:9093
          - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
            value: PLAINTEXT
          - name: KAFKA_CFG_LISTENERS
            value: PLAINTEXT://:9092,CONTROLLER://:9093
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka:9092
          - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          - name: KAFKA_CFG_NODE_ID
            value: "0"
          - name: KAFKA_CFG_PROCESS_ROLES
            value: controller,broker
          image: docker.io/bitnami/kafka:latest
          name: kafka
          ports:
          - containerPort: 9092
            protocol: TCP
          - containerPort: 9094
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - kafka
        from:
          kind: ImageStreamTag
          name: kafka:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: kafka
      app.kubernetes.io/component: kafka
      app.kubernetes.io/instance: kafka
    name: kafka
  spec:
    ports:
    - name: 9092-tcp
      port: 9092
      protocol: TCP
      targetPort: 9092
    - name: 9094-tcp
      port: 9094
      protocol: TCP
      targetPort: 9094
    selector:
      deploymentconfig: kafka
kind: List
metadata: {}
